
branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      python: "3.4"

    - os: linux
      python: "3.3.5"

    - os: linux
      python: "2.7"

cache:
  directories:
    - $HOME/.pyenv/versions/3.5.2
    - $HOME/.pyenv/versions/3.4.5
    - $HOME/.pyenv/versions/3.3.6
    - $HOME/.pyenv/versions/2.7.12
    - $HOME/downloads

install:
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - flake8
  - python setup.py sdist
  - python setup.py bdist_wheel
#  - python setup.py test

after_success:
#  - codecov -X gcov --required --file ./tests/coverage.xml

